name: CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp_version: ['24.3', '25.2']
        elixir_version: ['1.13', '1.14']

    name: CI pipeline (Elixir ${{matrix.elixir_version}} / OTP ${{matrix.otp_version}} )
    services:
      postgres:
        image: postgres:15
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: accounting_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with: 
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir_version}}
      - name: Restore mix dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/api/mix.lock') }}
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
